!depfile:get_sfxcpln.D
!auto_modi:get_sfxcpl_n.D
MODULE MODI_GET_SFXCPL_n 
INTERFACE
      SUBROUTINE GET_SFXCPL_n (I, S, U, W, &
                               HPROGRAM,KI,PRUI,PWIND,PFWSU,PFWSV,PSNET, &
                               PHEAT,PEVAP,PRAIN,PSNOW,PEVPR,PICEFLUX,   &
                               PFWSM,PPS,PHEAT_ICE,PEVAP_ICE,PSNET_ICE)  
USE MODD_ISBA_n, ONLY : ISBA_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
TYPE(ISBA_t), INTENT(INOUT) :: I
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(WATFLUX_t), INTENT(INOUT) :: W
 CHARACTER(LEN=6),    INTENT(IN)  :: HPROGRAM
INTEGER,             INTENT(IN)  :: KI      ! number of points
REAL, DIMENSION(KI), INTENT(OUT) :: PRUI
REAL, DIMENSION(KI), INTENT(OUT) :: PWIND
REAL, DIMENSION(KI), INTENT(OUT) :: PFWSU
REAL, DIMENSION(KI), INTENT(OUT) :: PFWSV
REAL, DIMENSION(KI), INTENT(OUT) :: PSNET
REAL, DIMENSION(KI), INTENT(OUT) :: PHEAT
REAL, DIMENSION(KI), INTENT(OUT) :: PEVAP
REAL, DIMENSION(KI), INTENT(OUT) :: PRAIN
REAL, DIMENSION(KI), INTENT(OUT) :: PSNOW
REAL, DIMENSION(KI), INTENT(OUT) :: PEVPR
REAL, DIMENSION(KI), INTENT(OUT) :: PICEFLUX
REAL, DIMENSION(KI), INTENT(OUT) :: PFWSM
REAL, DIMENSION(KI), INTENT(OUT) :: PPS
REAL, DIMENSION(KI), INTENT(OUT) :: PHEAT_ICE
REAL, DIMENSION(KI), INTENT(OUT) :: PEVAP_ICE
REAL, DIMENSION(KI), INTENT(OUT) :: PSNET_ICE
END SUBROUTINE GET_SFXCPL_n
END INTERFACE
END MODULE MODI_GET_SFXCPL_n 
