!depfile:put_sfx_sea.D
!auto_modi:put_sfx_sea.D
MODULE MODI_PUT_SFX_SEA 
INTERFACE
      SUBROUTINE PUT_SFX_SEA (S, U, W, &
                              KLUOUT,OCPL_SEAICE,OWATER,PSEA_SST,PSEA_UCU,        &
                             PSEA_VCU,PSEA_SST2,PSEA_UCU2,PSEA_VCU2,PSEAICE_SIT,PSEAICE_CVR,PSEAICE_ALB )  
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(WATFLUX_t), INTENT(INOUT) :: W
INTEGER,           INTENT(IN)  :: KLUOUT
LOGICAL,           INTENT(IN)  :: OCPL_SEAICE
LOGICAL,           INTENT(IN)  :: OWATER
REAL, DIMENSION(:), INTENT(IN) :: PSEA_SST
REAL, DIMENSION(:), INTENT(IN) :: PSEA_UCU
REAL, DIMENSION(:), INTENT(IN) :: PSEA_VCU
REAL, DIMENSION(:), INTENT(IN) :: PSEA_SST2 ! TBRIVOAL 2 SST
REAL, DIMENSION(:), INTENT(IN) :: PSEA_UCU2 ! TBRIVOAL 2 SST
REAL, DIMENSION(:), INTENT(IN) :: PSEA_VCU2 ! TBRIVOAL 2 SST
REAL, DIMENSION(:), INTENT(IN) :: PSEAICE_SIT
REAL, DIMENSION(:), INTENT(IN) :: PSEAICE_CVR
REAL, DIMENSION(:), INTENT(IN) :: PSEAICE_ALB
END SUBROUTINE PUT_SFX_SEA
END INTERFACE
END MODULE MODI_PUT_SFX_SEA 
